### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by masutaka** [masutaka/github-organization-watcher#3]
* [ ] Support GitHub pagination on `/orgs/:org_name/repos`
* [x] Login with GitHub OAuth Authorization instead of the Personal Access Token
* [x] Define root routing
* [ ] Improve decoration

**Comment by masutaka** [comment]
Switch to #10 and #11
